/**
 * Programme complet de 30 jours — 5 minutes par jour
 * Objectifs : perdre les joues du visage, perdre du poids, tonifier tout le corps
 *
 * Structure d'une séance (300s = 5 min) :
 *   - Échauffement : 30s
 *   - Circuit principal : 6 exercices × 40s = 240s
 *   - Récupération : 30s
 *
 * 4 phases de progression :
 *   - Jours  1-7  : Fondation       (doux, apprentissage)
 *   - Jours  8-14 : Progression      (intensité modérée)
 *   - Jours 15-21 : Intensification  (HIIT, amplitude)
 *   - Jours 22-30 : Maîtrise         (intensité maximale)
 */

export type ExerciseCategory =
  | 'face'
  | 'cardio'
  | 'tone'
  | 'warmup'
  | 'cooldown';

export type ProgramPhase =
  | 'Fondation'
  | 'Progression'
  | 'Intensification'
  | 'Maîtrise';

export interface Exercise {
  id: string;
  name: string;
  category: ExerciseCategory;
  image?: string;
  duration: number;
  description: string;
  instructions: string[];
  tips: string;
  targetMuscles: string;
  resourceId?: string;
}

export interface DayProgram {
  day: number;
  phase: ProgramPhase;
  title: string;
  subtitle: string;
  focus: string;
  duration: number;
  exercises: Exercise[];
  quote: string;
}

/* ------------------------------------------------------------------ */
/*  POULE D'EXERCICES — réutilisée et combinée sur 30 jours           */
/* ------------------------------------------------------------------ */

const E = {
  /* ----- ÉCHAUFFEMENT ----- */
  warmBreath: {
    id: 'warm-breath',
    name: 'Respiration dynamique',
    category: 'warmup' as const,
    image: 'ambient-cooldown',
    duration: 30,
    description:
      "Échauffement respiratoire pour oxygéner le corps et préparer les muscles.",
    instructions: [
      "Debout, pieds écartés largeur d'épaules",
      'Inspire profondément par le nez en levant les bras',
      'Expire par la bouche en descendant les bras',
      'Répète en gainant légèrement le ventre',
    ],
    tips: 'Garde le rythme 4 secondes inspiration, 4 secondes expiration.',
    targetMuscles: 'Diaphragme, épaules, circulation générale',
  },
  warmMarch: {
    id: 'warm-march',
    name: 'Marche sur place',
    category: 'warmup' as const,
    image: 'ex-cardio-knees',
    duration: 30,
    description: "Marche dynamique sur place pour réveiller tout le corps.",
    instructions: [
      'Marche sur place en levant bien les genoux',
      'Balance les bras naturellement',
      'Garde le buste droit et gainé',
      'Augmente progressivement le rythme',
    ],
    tips: 'Pose le pied à plat, sans à-coups.',
    targetMuscles: 'Jambes, mollets, épaules',
    resourceId: 'mixamo',
  },
  warmTwist: {
    id: 'warm-twist',
    name: 'Rotations du buste',
    category: 'warmup' as const,
    image: 'ambient-tone',
    duration: 30,
    description: "Rotations douces du tronc pour préparer le bas du corps.",
    instructions: [
      'Debout, pieds largeur épaules, bras croisés',
      'Pivote le buste à droite puis à gauche',
      'Garde les hanches stables',
      'Cherche l amplitude sans forcer',
    ],
    tips: 'Expire sur la rotation, inspire au centre.',
    targetMuscles: 'Obliques, bas du dos, épaules',
  },

  /* ----- VISAGE (perdre les joues) ----- */
  fishFace: {
    id: 'fish-face',
    name: 'Fish Face (joues creusées)',
    category: 'face' as const,
    image: 'ex-face-fish',
    duration: 45,
    description:
      "Exercice star pour affiner les joues : on creuse les joues en aspirant vers l'intérieur.",
    instructions: [
      'Aspire tes joues vers l intérieur comme un poisson',
      'Maintiens la contraction 5 secondes',
      'Relâche 2 secondes et recommence',
      'Garde le reste du visage détendu',
    ],
    tips:
      'Tu dois sentir tes joues coller aux dents. Plus tu tiens, plus le muscle tonifie.',
    targetMuscles: 'Muscles zygomatiques, buccinateur, joues',
    resourceId: 'gymvisual',
  },
  cheekLift: {
    id: 'cheek-lift',
    name: 'Sourire large (lift de joues)',
    category: 'face' as const,
    image: 'ex-face-cheek',
    duration: 45,
    description:
      "Sourire exagéré pour remonter les pommettes et tonifier les joues.",
    instructions: [
      'Souvre la bouche et souris le plus largement possible',
      'Pousse tes pommettes vers le haut',
      'Plisse légèrement les yeux',
      'Maintiens 10s, relâche 2s, recommence',
    ],
    tips: 'Imagine que tu souris avec tes oreilles : ça aide à bien lever les pommettes.',
    targetMuscles: 'Zygomatique majeur, pommettes, paupières',
    resourceId: 'sketchfab-yoga',
  },
  jawRelease: {
    id: 'jaw-release',
    name: 'Relâchement de mâchoire',
    category: 'face' as const,
    image: 'ex-face-jaw',
    duration: 45,
    description:
      "Mouvement de mâchoire pour affiner l'ovale du visage et relâcher les tensions.",
    instructions: [
      'Bouge la mâchoire alternativement à droite puis à gauche',
      'Ensuite, projette le menton vers l avant puis rentre-le',
      'Mouvement lent et contrôlé',
      'Respire régulièrement pendant le mouvement',
    ],
    tips: 'Pas de craquements forcés. Le mouvement doit rester fluide et sans douleur.',
    targetMuscles: 'Masséter, muscles masticateurs, ovale du visage',
    resourceId: 'gymvisual',
  },
  neckStretch: {
    id: 'neck-stretch',
    name: 'Étirement du cou',
    category: 'face' as const,
    image: 'ex-face-neck',
    duration: 45,
    description:
      "Étire le cou pour éliminer le double menton et drainer les joues.",
    instructions: [
      'Incline la tête vers la droite, oreille vers épaule',
      'Sentis l étirement sur le côté gauche du cou',
      'Reste 15s, change de côté',
      'Termine en regardant le plafond, menton vers le haut',
    ],
    tips: 'Épaules basses et détendues. Ne tire jamais brusquement la tête.',
    targetMuscles: 'Sterno-cléido-mastoïdien, platysma, sous-mental',
    resourceId: 'sketchfab-yoga',
  },
  lionFace: {
    id: 'lion-face',
    name: 'Face de lion',
    category: 'face' as const,
    image: 'ex-face-jaw',
    duration: 45,
    description:
      "Exercice yoga anti-âge : ouvrir grand la bouche et tirer la langue pour tonifier tout le visage.",
    instructions: [
      'Ouvre grand la bouche et les yeux',
      'Tire la langue vers le bas le plus loin possible',
      'Contracte tout le visage vers l extérieur',
      'Maintiens 5s, relâche 2s, répète',
    ],
    tips: 'C est l exercice le plus complet pour le bas du visage et le double menton.',
    targetMuscles: 'Platysma, langue, joues, paupières',
    resourceId: 'sketchfab-yoga',
  },
  chinLift: {
    id: 'chin-lift',
    name: 'Élévation du menton',
    category: 'face' as const,
    image: 'ex-face-neck',
    duration: 45,
    description:
      "Lève le menton vers le plafond pour cibler le double menton et le cou.",
    instructions: [
      'Redresse la tête, regarde le plafond',
      'Pousse le menton vers le haut et l avant',
      'Fais un baiser vers le ciel en contractant le cou',
      'Maintiens 5s, relâche, répète',
    ],
    tips: 'Tu dois sentir le bas du menton travailler intensément.',
    targetMuscles: 'Platysma, muscles sous-mentonniers',
    resourceId: 'gymvisual',
  },
  tonguePress: {
    id: 'tongue-press',
    name: 'Pression de langue au palais',
    category: 'face' as const,
    image: 'ex-face-fish',
    duration: 45,
    description:
      "Exercice discret pour affiner la mâchoire : la langue presse le palais.",
    instructions: [
      'Place la langue contre le palais, juste derrière les dents',
      'Appuie fermement vers le haut',
      'Maintiens la pression 10s',
      'Relâche 3s et recommence',
    ],
    tips: 'Exercice parfait à refaire dans la journée : dans les transports, au bureau.',
    targetMuscles: 'Langue, muscles masticateurs, ovale du visage',
  },

  /* ----- CARDIO (perdre du poids) ----- */
  jumpingJacks: {
    id: 'jumping-jacks',
    name: 'Jumping Jacks',
    category: 'cardio' as const,
    image: 'ex-cardio-jacks',
    duration: 45,
    description:
      "Le grand classique du cardio : saut écarté bras-jambes pour brûler un max de calories.",
    instructions: [
      'Débout, pieds joints, bras le long du corps',
      'Saille en écartant jambes et bras au-dessus de la tête',
      'Reviens en sautant à la position de départ',
      'Garde un rythme soutenu et régulier',
    ],
    tips: 'Atterris genoux légèrement fléchis pour protéger les articulations.',
    targetMuscles: 'Cardio, épaules, mollets, cuisses',
    resourceId: 'mixamo',
  },
  highKnees: {
    id: 'high-knees',
    name: 'Montées de genoux',
    category: 'cardio' as const,
    image: 'ex-cardio-knees',
    duration: 45,
    description:
      "Course sur place en montant les genoux à hauteur de hanche : cardio explosif.",
    instructions: [
      'Court sur place en montant les genoux haut',
      'Vise la hauteur de hanche avec chaque genou',
      'Balanced les bras en opposition',
      'Reste sur la pointe des pieds',
    ],
    tips: 'Gainage abdominal serré pour protéger le dos.',
    targetMuscles: 'Cardio, abdos, fléchisseurs de hanche, quadriceps',
    resourceId: 'mixamo',
  },
  mountainClimbers: {
    id: 'mountain-climbers',
    name: 'Mountain Climbers',
    category: 'cardio' as const,
    image: 'ex-cardio-climbers',
    duration: 45,
    description:
      "Position de planche, genoux alternés vers la poitrine : cardio + abdos explosifs.",
    instructions: [
      'Position de planche haute, mains sous les épaules',
      'Ramène un genou vers la poitrine',
      'Alterne rapidement les jambes comme en course',
      'Garde les hanches stables, ne lève pas les fesses',
    ],
    tips: 'Plus tu vas vite, plus le cardio travaille. Commence lentement pour bien placer.',
    targetMuscles: 'Cardio, abdos, obliques, épaules',
    resourceId: 'mixamo',
  },
  squatJumps: {
    id: 'squat-jumps',
    name: 'Sauts en squat',
    category: 'cardio' as const,
    image: 'ex-tone-squat',
    duration: 45,
    description:
      "Squat explosif avec saut : brûle des calories et tonifie les jambes.",
    instructions: [
      'Pieds largeur épaules, descends en squat',
      'Pousse explosivement vers le haut en sautant',
      'Atterris en douceur, genoux fléchis',
      'Enchaîne immédiatement le squat suivant',
    ],
    tips: 'Si tu entends un bruit en atterrissant, atterris trop lourdement. Sois léger.',
    targetMuscles: 'Cardio, quadriceps, fessiers, mollets',
    resourceId: 'mixamo',
  },
  burpees: {
    id: 'burpees',
    name: 'Burpees simplifiés',
    category: 'cardio' as const,
    image: 'ex-cardio-jacks',
    duration: 45,
    description:
      "Exercice complet : squat, planche, saut. Version accessible sans pompe complète.",
    instructions: [
      'Débout, descends en squat et pose les mains au sol',
      'Saute les pieds en arrière en position planche',
      'Ramène les pieds vers les mains',
      'Relève-toi avec un petit saut et bras au ciel',
    ],
    tips: 'Version débutant : remonte une jambe à la fois en arrière pour ménager le dos.',
    targetMuscles: 'Corps entier, cardio explosif',
    resourceId: 'darebee',
  },
  skaters: {
    id: 'skaters',
    name: 'Patineurs latéraux',
    category: 'cardio' as const,
    image: 'ex-cardio-knees',
    duration: 45,
    description:
      "Sauts latéraux d'un pied sur l'autre comme un patineur : cardio + équilibre.",
    instructions: [
      'Saute latéralement sur le pied droit',
      'Passe la jambe gauche derrière en croisé',
      'Saule ensuite sur le pied gauche',
      'Enchaîne en restant léger et rapide',
    ],
    tips: 'Abras les bras pour t équilibrer. Vise la largeur plutôt que la hauteur.',
    targetMuscles: 'Cardio, fessiers moyens, abducteurs',
    resourceId: 'mixamo',
  },

  /* ----- TONIFICATION (corps entier) ----- */
  squat: {
    id: 'squat',
    name: 'Squat',
    category: 'tone' as const,
    image: 'ex-tone-squat',
    duration: 45,
    description:
      "Roi des exercices : squat pour fessiers, cuisses et force du bas du corps.",
    instructions: [
      'Pieds largeur épaules, pointes légèrement en dehors',
      'Descends en poussant les fesses vers l arrière',
      'Cuisses parallèles au sol (ou plus haut si débutant)',
      'Remonte en poussant sur les talons',
    ],
    tips: 'Genoux dans l axe des pointes de pieds. Dos droit, regard vers l avant.',
    targetMuscles: 'Quadriceps, fessiers, ischio-jambiers',
    resourceId: 'muscle-and-strength',
  },
  plank: {
    id: 'plank',
    name: 'Planche (gainage)',
    category: 'tone' as const,
    image: 'ex-tone-plank',
    duration: 45,
    description:
      "Gainage statique : corps droit sur les avant-bras. Le meilleur pour la sangle abdominale.",
    instructions: [
      'Avant-bras au sol, coudes sous les épaules',
      'Corps aligné de la tête aux talons',
      'Contracte les abdos et les fessiers',
      'Ne laisse pas les hanches descendre',
    ],
    tips: 'Respire calmement. Si ça tremble, c est normal : c est le muscle qui travaille.',
    targetMuscles: 'Abdos profonds, transverse, lombaires',
    resourceId: 'muscle-and-strength',
  },
  lunge: {
    id: 'lunge',
    name: 'Fentes',
    category: 'tone' as const,
    image: 'ex-tone-lunge',
    duration: 45,
    description:
      "Fentes alternées pour travailler unilatéralement fessiers et cuisses.",
    instructions: [
      'Débout, fais un grand pas en avant',
      'Descends en pliant les deux genoux à 90°',
      'Le genou arrière effleure le sol',
      'Pousse sur le talon avant pour remonter',
    ],
    tips: 'Le genou avant ne dépasse pas la pointe du pied. Buste droit.',
    targetMuscles: 'Quadriceps, fessiers, ischio-jambiers',
    resourceId: 'muscle-and-strength',
  },
  gluteBridge: {
    id: 'glute-bridge',
    name: 'Pont fessier',
    category: 'tone' as const,
    image: 'ex-tone-bridge',
    duration: 45,
    description:
      "Allongé sur le dos, soulève le bassin pour tonifier fessiers et bas du dos.",
    instructions: [
      'Allongé sur le dos, pieds à plat, genoux pliés',
      'Pousse sur les talons pour lever le bassin',
      'Aligne genoux-hanches-épaules en haut',
      'Contracte les fessiers 2s en haut, redesends',
    ],
    tips: 'Pousse depuis les talons, pas les pointes. Serre les fessiers en haut.',
    targetMuscles: 'Grand fessier, ischio-jambiers, bas du dos',
    resourceId: 'muscle-and-strength',
  },
  pushups: {
    id: 'pushups',
    name: 'Pompes (adaptées)',
    category: 'tone' as const,
    image: 'ex-tone-plank',
    duration: 45,
    description:
      "Pompes sur les genoux ou contre un mur : haut du corps et gainage.",
    instructions: [
      'Mains au sol largeur épaules',
      'Version accessible : genoux au sol, chevules croisés',
      'Descends la poitrine vers le sol, coudes à 45°',
      'Pousse pour remonter en gainant les abdos',
    ],
    tips: 'Mieux vaut 5 pompes parfaites que 15 mal exécutées. Garde le corps aligné.',
    targetMuscles: 'Pectoraux, triceps, épaules, abdos',
    resourceId: 'muscle-and-strength',
  },
  bicycleCrunch: {
    id: 'bicycle-crunch',
    name: 'Crunch vélo',
    category: 'tone' as const,
    image: 'ex-tone-bridge',
    duration: 45,
    description:
      "Abdos en mouvement vélo : coudes vers genou opposé pour tout le buste.",
    instructions: [
      'Allongé, mains derrière la tête',
      'Ramène le coude droit vers le genou gauche',
      'Étends la jambe droite en même temps',
      'Alterne comme en pédalant',
    ],
    tips: 'Ne tire pas sur la nuque. Les abdos font le travail, pas les bras.',
    targetMuscles: 'Grands droits, obliques',
    resourceId: 'darebee',
  },
  wallSit: {
    id: 'wall-sit',
    name: 'Chaise contre un mur',
    category: 'tone' as const,
    image: 'ex-tone-squat',
    duration: 45,
    description:
      "Position assise immobile contre un mur : endurance des cuisses.",
    instructions: [
      'Dos contre un mur, descends jusqu à avoir les genoux à 90°',
      'Cuisses parallèles au sol',
      'Maintiens la position immobile',
      'Poids dans les talons',
    ],
    tips: 'Si ça brûle, c est parfait. Respire profondément et tiens.',
    targetMuscles: 'Quadriceps, fessiers',
    resourceId: 'darebee',
  },

  /* ----- RÉCUPÉRATION ----- */
  coolStretch: {
    id: 'cool-stretch',
    name: 'Étirement global',
    category: 'cooldown' as const,
    image: 'ambient-cooldown',
    duration: 30,
    description:
      "Récupération active : étire tout le corps pour relâcher les tensions.",
    instructions: [
      'Étire les bras vers le ciel, respire profondément',
      'Penche-toi vers l avant pour étirer le dos',
      'Roule doucement pour remonter vertèbre par vertèbre',
      'Termine par 3 respirations profondes',
    ],
    tips: 'Pas de rebond. Étire en douceur, 20s par position.',
    targetMuscles: 'Dos, ischio-jambiers, épaules',
    resourceId: 'sketchfab-yoga',
  },
  coolBreath: {
    id: 'cool-breath',
    name: 'Respiration apaisante',
    category: 'cooldown' as const,
    image: 'ambient-cooldown',
    duration: 30,
    description:
      "Respiration finale pour faire redescendre le rythme cardiaque.",
    instructions: [
      'Débout ou assis, dos droit',
      'Inspire 4s par le nez, gonfle le ventre',
      'Retiens 2s',
      'Expire 6s par la bouche',
    ],
    tips: 'L expiration plus longue que l inspiration active le système parasympathique (calme).',
    targetMuscles: 'Système nerveux, récupération',
    resourceId: 'sketchfab-yoga',
  },

  /* ----- NOUVEAUX ABDOS / CORE ----- */
  russianTwist: {
    id: 'russian-twist',
    name: 'Twist russe',
    category: 'tone' as const,
    image: 'ex-tone-bridge',
    duration: 45,
    description: "Assis, buste penché en arrière, rotation du tronc côté à côté.",
    instructions: [
      'Assis, genoux fléchis, pieds décollés optionnel',
      'Penche le buste en arrière à 45°',
      'Tourne le tronc à droite puis à gauche',
      'Touche le sol de chaque côté',
    ],
    tips: 'Garde le dos droit. Plus tu penches en arrière, plus c est intense.',
    targetMuscles: 'Obliques, transverse',
    resourceId: 'muscle-and-strength',
  },
  legRaises: {
    id: 'leg-raises',
    name: 'Jambes levées',
    category: 'tone' as const,
    image: 'ex-tone-bridge',
    duration: 45,
    description: "Allongé, lève les jambes tendues vers le ciel puis descends sans toucher le sol.",
    instructions: [
      'Allongé sur le dos, mains sous les fesses',
      'Lève les jambes tendues à 90°',
      'Descends lentement sans poser au sol',
      'Remonte en controlant',
    ],
    tips: 'Bas du dos collé au sol. Si ça tire, plie légèrement les genoux.',
    targetMuscles: 'Bas des abdos, fléchisseurs de hanche',
    resourceId: 'muscle-and-strength',
  },
  flutterKicks: {
    id: 'flutter-kicks',
    name: 'Ciseaux (flutter kicks)',
    category: 'tone' as const,
    image: 'ex-tone-bridge',
    duration: 45,
    description: "Allongé, jambes tendues qui montent et descendent alternativement.",
    instructions: [
      'Allongé, mains sous les fesses, jambes tendues',
      'Lève une jambe pendant que l autre descend',
      'Alternance rapide en ciseaux',
      'Ne pose jamais les pieds',
    ],
    tips: 'Petits mouvements amples, bas du dos collé au sol.',
    targetMuscles: 'Bas des abdos, fléchisseurs de hanche',
    resourceId: 'darebee',
  },
  deadBug: {
    id: 'dead-bug',
    name: 'Dead bug (insecte mort)',
    category: 'tone' as const,
    image: 'ex-tone-bridge',
    duration: 45,
    description: "Allongé, alterne extension bras-jambe opposée en gardant le dos collé.",
    instructions: [
      'Allongé, bras vers le ciel, genoux à 90°',
      'Étends bras droit + jambe gauche au sol',
      'Reviens au centre',
      'Alterne bras gauche + jambe droite',
    ],
    tips: 'Le bas du dos reste collé au sol en permanence.',
    targetMuscles: 'Abdos profonds, transverse',
    resourceId: 'ace-fitness-library',
  },
  sidePlank: {
    id: 'side-plank',
    name: 'Planche latérale',
    category: 'tone' as const,
    image: 'ex-tone-plank',
    duration: 45,
    description: "Gainage latéral sur un avant-bras, corps aligné.",
    instructions: [
      'Sur le côté, avant-bras au sol, coude sous l épaule',
      'Lève le bassin, corps aligné tête-pieds',
      'Maintiens la position immobile',
      'Change de côté à mi-temps',
    ],
    tips: 'Hanches hautes, ne laisse pas le bassin tomber.',
    targetMuscles: 'Obliques, stabilisateurs',
    resourceId: 'muscle-and-strength',
  },
  hollowHold: {
    id: 'hollow-hold',
    name: 'Gainage creux (hollow)',
    category: 'tone' as const,
    image: 'ex-tone-bridge',
    duration: 45,
    description: "Position creuse : bas du dos collé, jambes et bras décollés.",
    instructions: [
      'Allongé, bas du dos collé au sol',
      'Lève jambes tendues à 30°',
      'Épaules décollées, bras tendus vers l arrière',
      'Maintiens la position creuse',
    ],
    tips: 'Si le dos décolle, monte les jambes un peu.',
    targetMuscles: 'Abdos profonds, transverse',
    resourceId: 'darebee',
  },

  /* ----- NOUVELLE TONIFICATION ----- */
  tricepDips: {
    id: 'tricep-dips',
    name: 'Dips triceps',
    category: 'tone' as const,
    image: 'ex-tone-plank',
    duration: 45,
    description: "Sur une chaise ou au sol, fléchis les coudes pour les triceps.",
    instructions: [
      'Assis au bord d une chaise, mains agrippées au bord',
      'Fesse décollée, descends en pliant les coudes',
      'Coudes à 90°, remonte en poussant',
      'Jambes tendues ou pliées selon le niveau',
    ],
    tips: 'Coudes pointent vers l arrière, pas vers les côtés.',
    targetMuscles: 'Triceps, épaules avant',
    resourceId: 'muscle-and-strength',
  },
  calfRaises: {
    id: 'calf-raises',
    name: 'Montées sur pointes',
    category: 'tone' as const,
    image: 'ex-tone-squat',
    duration: 45,
    description: "Debout, monte sur la pointe des pieds pour les mollets.",
    instructions: [
      'Debout, pieds largeur épaules',
      'Pousse sur les pointes pour lever les talons',
      'Monte le plus haut possible',
      'Descends lentement en controlant',
    ],
    tips: 'Mouvement lent et contrôlé.',
    targetMuscles: 'Mollets (gastrocnémien, soléaire)',
    resourceId: 'muscle-and-strength',
  },
  superman: {
    id: 'superman',
    name: 'Superman (dos)',
    category: 'tone' as const,
    image: 'ex-tone-bridge',
    duration: 45,
    description: "Allongé sur le ventre, lève bras et jambes pour le bas du dos.",
    instructions: [
      'Allongé sur le ventre, bras tendus devant',
      'Lève bras + jambes en même temps',
      'Maintiens 2s en haut',
      'Descends lentement',
    ],
    tips: 'Regard vers le sol pour protéger la nuque.',
    targetMuscles: 'Bas du dos, fessiers, épaules',
    resourceId: 'muscle-and-strength',
  },
  birdDog: {
    id: 'bird-dog',
    name: 'Bird dog',
    category: 'tone' as const,
    image: 'ex-tone-plank',
    duration: 45,
    description: "À quatre pattes, étends bras + jambe opposée.",
    instructions: [
      'À quatre pattes, mains sous les épaules',
      'Étends bras droit devant + jambe gauche derrière',
      'Maintiens 2s, corps aligné',
      'Alterne côté opposé',
    ],
    tips: 'Bassin stable, ne bascule pas.',
    targetMuscles: 'Dos, abdos, fessiers, équilibre',
    resourceId: 'ace-fitness-library',
  },
  shoulderTaps: {
    id: 'shoulder-taps',
    name: 'Tapotements d épaules',
    category: 'tone' as const,
    image: 'ex-tone-plank',
    duration: 45,
    description: "Position planche, touche chaque épaule avec la main opposée.",
    instructions: [
      'Position de planche haute, mains sous les épaules',
      'Touche l épaule droite avec la main gauche',
      'Repose la main, alterne',
      'Garde les hanches stables',
    ],
    tips: 'Hanches immobiles = abdos au travail.',
    targetMuscles: 'Épaules, abdos, stabilisateurs',
    resourceId: 'darebee',
  },
  reverseLunge: {
    id: 'reverse-lunge',
    name: 'Fentes arrière',
    category: 'tone' as const,
    image: 'ex-tone-lunge',
    duration: 45,
    description: "Fente en pas arrière : ménage mieux les genoux.",
    instructions: [
      'Debout, fais un grand pas en arrière',
      'Descends en pliant les deux genoux à 90°',
      'Le genou avant ne dépasse pas la pointe du pied',
      'Pousse sur le talon avant pour remonter',
    ],
    tips: 'Buste droit, regard vers l avant.',
    targetMuscles: 'Quadriceps, fessiers, ischio-jambiers',
    resourceId: 'muscle-and-strength',
  },
  sumoSquat: {
    id: 'sumo-squat',
    name: 'Squat sumo',
    category: 'tone' as const,
    image: 'ex-tone-squat',
    duration: 45,
    description: "Squat pieds très écartés : cible l intérieur des cuisses.",
    instructions: [
      'Pieds très écartés, pointes en dehors à 45°',
      'Descends en poussant les genoux vers l extérieur',
      'Cuisses parallèles au sol',
      'Remonte en poussant sur les talons',
    ],
    tips: 'Genoux dans l axe des pointes de pieds.',
    targetMuscles: 'Adducteurs, fessiers, quadriceps',
    resourceId: 'muscle-and-strength',
  },
  gluteKickback: {
    id: 'glute-kickback',
    name: 'Kickback fessier',
    category: 'tone' as const,
    image: 'ex-tone-plank',
    duration: 45,
    description: "À quatre pattes, pousse une jambe vers l arrière pour le fessier.",
    instructions: [
      'À quatre pattes, mains sous les épaules',
      'Pousse une jambe pliée vers l arrière et le haut',
      'Contracte le fessier en haut',
      'Alterne les jambes',
    ],
    tips: 'Dos stable, ne cambre pas.',
    targetMuscles: 'Grand fessier, ischio-jambiers',
    resourceId: 'muscle-and-strength',
  },
  plankUp: {
    id: 'plank-up',
    name: 'Planche montante',
    category: 'tone' as const,
    image: 'ex-tone-plank',
    duration: 45,
    description: "Alterne planche haute (mains) et planche basse (avant-bras).",
    instructions: [
      'Commence en planche haute (mains au sol)',
      'Descends sur l avant-bras droit puis gauche',
      'Remonte main droite puis main gauche',
      'Enchaîne sans pause',
    ],
    tips: 'Hanches stables, ne balance pas.',
    targetMuscles: 'Épaules, abdos, triceps',
    resourceId: 'darebee',
  },
};

/* ------------------------------------------------------------------ */
/*  PROGRAMME 30 JOURS                                                 */
/* ------------------------------------------------------------------ */

export const program: DayProgram[] = [
  {
    day: 1,
    phase: 'Fondation',
    title: 'Premier élan',
    subtitle: 'Découverte en douceur',
    focus: "Lance la machine en douceur.",
    duration: 600,
    exercises: [
      E.warmBreath,
      E.fishFace,
      E.cheekLift,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.plank,
      E.bicycleCrunch,
      E.russianTwist,
      E.legRaises,
      E.squat,
      E.lunge,
      E.gluteBridge,
      E.coolStretch,
    ],
    quote: 'Un voyage de mille kilomètres commence par un seul pas.',
  },
  {
    day: 2,
    phase: 'Fondation',
    title: 'Réveil du visage',
    subtitle: 'Cible les joues',
    focus: "Focus joues + cardio modéré.",
    duration: 600,
    exercises: [
      E.warmMarch,
      E.jawRelease,
      E.neckStretch,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.flutterKicks,
      E.deadBug,
      E.sidePlank,
      E.hollowHold,
      E.pushups,
      E.wallSit,
      E.tricepDips,
      E.coolBreath,
    ],
    quote: "La constance bat l'intensité. Montre-toi chaque jour.",
  },
  {
    day: 3,
    phase: 'Fondation',
    title: 'Cœur et jambes',
    subtitle: 'Cardio + tonification',
    focus: "Cardio et bas du corps.",
    duration: 600,
    exercises: [
      E.warmTwist,
      E.lionFace,
      E.chinLift,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.birdDog,
      E.shoulderTaps,
      E.plankUp,
      E.plank,
      E.calfRaises,
      E.superman,
      E.reverseLunge,
      E.coolStretch,
    ],
    quote: 'Ton corps est capable de bien plus que tu ne le penses.',
  },
  {
    day: 4,
    phase: 'Fondation',
    title: 'Affinage du visage',
    subtitle: 'Joues + menton',
    focus: "Affine l'ovale du visage.",
    duration: 600,
    exercises: [
      E.warmBreath,
      E.tonguePress,
      E.fishFace,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.bicycleCrunch,
      E.russianTwist,
      E.legRaises,
      E.flutterKicks,
      E.sumoSquat,
      E.gluteKickback,
      E.squat,
      E.coolBreath,
    ],
    quote: 'Les petites actions répétées chaque jour deviennent de grands changements.',
  },
  {
    day: 5,
    phase: 'Fondation',
    title: 'Gainage et cardio',
    subtitle: 'Abdos + rythme',
    focus: "Découvre le gainage.",
    duration: 600,
    exercises: [
      E.warmMarch,
      E.cheekLift,
      E.jawRelease,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.deadBug,
      E.sidePlank,
      E.hollowHold,
      E.birdDog,
      E.lunge,
      E.gluteBridge,
      E.pushups,
      E.coolStretch,
    ],
    quote: "La douleur d'aujourd'hui est la force de demain.",
  },
  {
    day: 6,
    phase: 'Fondation',
    title: 'Visage de lion',
    subtitle: 'Yoga facial complet',
    focus: "Intègre la face de lion.",
    duration: 600,
    exercises: [
      E.warmTwist,
      E.neckStretch,
      E.lionFace,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.shoulderTaps,
      E.plankUp,
      E.plank,
      E.bicycleCrunch,
      E.wallSit,
      E.tricepDips,
      E.calfRaises,
      E.coolBreath,
    ],
    quote: "Prends soin de ton corps. C'est le seul endroit où tu es obligé de vivre.",
  },
  {
    day: 7,
    phase: 'Fondation',
    title: 'Bilan de semaine 1',
    subtitle: 'On consolide',
    focus: "Récapitulatif de la semaine.",
    duration: 600,
    exercises: [
      E.warmBreath,
      E.chinLift,
      E.tonguePress,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.russianTwist,
      E.legRaises,
      E.flutterKicks,
      E.deadBug,
      E.superman,
      E.reverseLunge,
      E.sumoSquat,
      E.coolStretch,
    ],
    quote: 'Une semaine déjà. Tu as fait le plus dur : commencer.',
  },
  {
    day: 8,
    phase: 'Progression',
    title: 'On monte en intensité',
    subtitle: 'Cardio plus soutenu',
    focus: "Mountain climbers et intensité.",
    duration: 600,
    exercises: [
      E.warmMarch,
      E.fishFace,
      E.cheekLift,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.sidePlank,
      E.hollowHold,
      E.birdDog,
      E.shoulderTaps,
      E.gluteKickback,
      E.squat,
      E.lunge,
      E.coolBreath,
    ],
    quote: "Le succès, c'est se relever une fois de plus qu'on est tombé.",
  },
  {
    day: 9,
    phase: 'Progression',
    title: 'Haut du corps',
    subtitle: 'Découverte des pompes',
    focus: "Haut du corps + triceps.",
    duration: 600,
    exercises: [
      E.warmTwist,
      E.jawRelease,
      E.neckStretch,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.plankUp,
      E.plank,
      E.bicycleCrunch,
      E.russianTwist,
      E.gluteBridge,
      E.pushups,
      E.wallSit,
      E.coolStretch,
    ],
    quote: "Ne compare pas tes débuts à la fin de quelqu'un d'autre.",
  },
  {
    day: 10,
    phase: 'Progression',
    title: 'Brûle calories',
    subtitle: 'HIIT modéré',
    focus: "Enchaînement cardio rapide.",
    duration: 600,
    exercises: [
      E.warmBreath,
      E.lionFace,
      E.chinLift,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.legRaises,
      E.flutterKicks,
      E.deadBug,
      E.sidePlank,
      E.tricepDips,
      E.calfRaises,
      E.superman,
      E.coolBreath,
    ],
    quote: "La sueur d'aujourd'hui est le succès de demain.",
  },
  {
    day: 11,
    phase: 'Progression',
    title: 'Fessiers et cuisses',
    subtitle: 'Spécial bas du corps',
    focus: "Galbe et brûle.",
    duration: 600,
    exercises: [
      E.warmMarch,
      E.tonguePress,
      E.fishFace,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.hollowHold,
      E.birdDog,
      E.shoulderTaps,
      E.plankUp,
      E.reverseLunge,
      E.sumoSquat,
      E.gluteKickback,
      E.coolStretch,
    ],
    quote: "Ton corps peut presque tout. C'est ton esprit qu'il faut convaincre.",
  },
  {
    day: 12,
    phase: 'Progression',
    title: 'Abdos et visage',
    subtitle: 'Sangle abdominale',
    focus: "Obliques et ventre plat.",
    duration: 600,
    exercises: [
      E.warmTwist,
      E.cheekLift,
      E.jawRelease,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.plank,
      E.bicycleCrunch,
      E.russianTwist,
      E.legRaises,
      E.squat,
      E.lunge,
      E.gluteBridge,
      E.coolBreath,
    ],
    quote: "Ce n'est pas ce que tu fais de temps en temps, mais ce que tu fais chaque jour.",
  },
  {
    day: 13,
    phase: 'Progression',
    title: 'Endurance',
    subtitle: 'Chaise contre mur',
    focus: "Endurance des cuisses.",
    duration: 600,
    exercises: [
      E.warmBreath,
      E.neckStretch,
      E.lionFace,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.flutterKicks,
      E.deadBug,
      E.sidePlank,
      E.hollowHold,
      E.pushups,
      E.wallSit,
      E.tricepDips,
      E.coolStretch,
    ],
    quote: "Quand ça brûle, c'est que le changement est en train de se faire.",
  },
  {
    day: 14,
    phase: 'Progression',
    title: 'Cap de la moitié',
    subtitle: 'Bilan semaine 2',
    focus: "Récapitulatif intensif.",
    duration: 600,
    exercises: [
      E.warmMarch,
      E.chinLift,
      E.tonguePress,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.birdDog,
      E.shoulderTaps,
      E.plankUp,
      E.plank,
      E.calfRaises,
      E.superman,
      E.reverseLunge,
      E.coolBreath,
    ],
    quote: "Tu es plus fort maintenant qu'il y a 14 jours. Continue.",
  },
  {
    day: 15,
    phase: 'Intensification',
    title: 'HIIT explosif',
    subtitle: 'Sauts en squat',
    focus: "Puissance des jambes.",
    duration: 600,
    exercises: [
      E.warmTwist,
      E.fishFace,
      E.cheekLift,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.bicycleCrunch,
      E.russianTwist,
      E.legRaises,
      E.flutterKicks,
      E.sumoSquat,
      E.gluteKickback,
      E.squat,
      E.coolStretch,
    ],
    quote: 'La magie opère en dehors de ta zone de confort.',
  },
  {
    day: 16,
    phase: 'Intensification',
    title: 'Burpees accessibles',
    subtitle: 'Corps complet',
    focus: "L'exercice le plus complet.",
    duration: 600,
    exercises: [
      E.warmBreath,
      E.jawRelease,
      E.neckStretch,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.deadBug,
      E.sidePlank,
      E.hollowHold,
      E.birdDog,
      E.lunge,
      E.gluteBridge,
      E.pushups,
      E.coolBreath,
    ],
    quote: 'Tu ne sais pas de quoi tu es capable tant que tu ne te pousses pas.',
  },
  {
    day: 17,
    phase: 'Intensification',
    title: 'Patineurs et agilité',
    subtitle: 'Cardio latéral',
    focus: "Équilibre et abducteurs.",
    duration: 600,
    exercises: [
      E.warmMarch,
      E.lionFace,
      E.chinLift,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.shoulderTaps,
      E.plankUp,
      E.plank,
      E.bicycleCrunch,
      E.wallSit,
      E.tricepDips,
      E.calfRaises,
      E.coolStretch,
    ],
    quote: "L'agilité du corps naît de la régularité de l'effort.",
  },
  {
    day: 18,
    phase: 'Intensification',
    title: 'Force et volume',
    subtitle: 'Haut + bas du corps',
    focus: "Tout le corps en force.",
    duration: 600,
    exercises: [
      E.warmTwist,
      E.tonguePress,
      E.fishFace,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.russianTwist,
      E.legRaises,
      E.flutterKicks,
      E.deadBug,
      E.superman,
      E.reverseLunge,
      E.sumoSquat,
      E.coolBreath,
    ],
    quote: "La force n'est pas une question de taille, mais de régularité.",
  },
  {
    day: 19,
    phase: 'Intensification',
    title: 'Brûle-max cardio',
    subtitle: 'HIIT long',
    focus: "Calorie bomb.",
    duration: 600,
    exercises: [
      E.warmBreath,
      E.cheekLift,
      E.jawRelease,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.sidePlank,
      E.hollowHold,
      E.birdDog,
      E.shoulderTaps,
      E.gluteKickback,
      E.squat,
      E.lunge,
      E.coolStretch,
    ],
    quote: "Le corps atteint ce que l'esprit croit. Crois en toi.",
  },
  {
    day: 20,
    phase: 'Intensification',
    title: 'Gainage extrême',
    subtitle: 'Core et posture',
    focus: "Gainage intensif.",
    duration: 600,
    exercises: [
      E.warmMarch,
      E.neckStretch,
      E.lionFace,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.plankUp,
      E.plank,
      E.bicycleCrunch,
      E.russianTwist,
      E.gluteBridge,
      E.pushups,
      E.wallSit,
      E.coolBreath,
    ],
    quote: 'Un core fort, un dos sauvé pour la vie.',
  },
  {
    day: 21,
    phase: 'Intensification',
    title: 'Cap des 3 semaines',
    subtitle: 'Bilan semaine 3',
    focus: "Test complet.",
    duration: 600,
    exercises: [
      E.warmTwist,
      E.chinLift,
      E.tonguePress,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.legRaises,
      E.flutterKicks,
      E.deadBug,
      E.sidePlank,
      E.tricepDips,
      E.calfRaises,
      E.superman,
      E.coolStretch,
    ],
    quote: "21 jours. Tu n'es plus le même.",
  },
  {
    day: 22,
    phase: 'Maîtrise',
    title: 'Explosivité',
    subtitle: 'Sauts et puissance',
    focus: "Puissance maximale.",
    duration: 600,
    exercises: [
      E.warmBreath,
      E.fishFace,
      E.cheekLift,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.hollowHold,
      E.birdDog,
      E.shoulderTaps,
      E.plankUp,
      E.reverseLunge,
      E.sumoSquat,
      E.gluteKickback,
      E.coolBreath,
    ],
    quote: "La puissance, c'est la force appliquée vite.",
  },
  {
    day: 23,
    phase: 'Maîtrise',
    title: 'Corps complet HIIT',
    subtitle: 'Burpees et pompes',
    focus: "Haut et cardio.",
    duration: 600,
    exercises: [
      E.warmMarch,
      E.jawRelease,
      E.neckStretch,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.plank,
      E.bicycleCrunch,
      E.russianTwist,
      E.legRaises,
      E.squat,
      E.lunge,
      E.gluteBridge,
      E.coolStretch,
    ],
    quote: "Le corps complet, c'est l'efficacité maximale.",
  },
  {
    day: 24,
    phase: 'Maîtrise',
    title: "Jambes d'acier",
    subtitle: 'Endurance bas du corps',
    focus: "Les jambes parlent.",
    duration: 600,
    exercises: [
      E.warmTwist,
      E.lionFace,
      E.chinLift,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.flutterKicks,
      E.deadBug,
      E.sidePlank,
      E.hollowHold,
      E.pushups,
      E.wallSit,
      E.tricepDips,
      E.coolBreath,
    ],
    quote: 'Les jambes fortes portent un esprit fort.',
  },
  {
    day: 25,
    phase: 'Maîtrise',
    title: 'Cardio infernal',
    subtitle: 'HIIT maximal',
    focus: "Le cardio le plus intense.",
    duration: 600,
    exercises: [
      E.warmBreath,
      E.tonguePress,
      E.fishFace,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.birdDog,
      E.shoulderTaps,
      E.plankUp,
      E.plank,
      E.calfRaises,
      E.superman,
      E.reverseLunge,
      E.coolStretch,
    ],
    quote: 'Quand tu veux abandonner, souviens-toi pourquoi tu as commencé.',
  },
  {
    day: 26,
    phase: 'Maîtrise',
    title: 'Visage sculpté',
    subtitle: 'Yoga facial avancé',
    focus: "Tous les exercices faciaux.",
    duration: 600,
    exercises: [
      E.warmMarch,
      E.cheekLift,
      E.jawRelease,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.bicycleCrunch,
      E.russianTwist,
      E.legRaises,
      E.flutterKicks,
      E.sumoSquat,
      E.gluteKickback,
      E.squat,
      E.coolBreath,
    ],
    quote: 'Un visage détendu est un visage rayonnant.',
  },
  {
    day: 27,
    phase: 'Maîtrise',
    title: 'Force et volume',
    subtitle: 'Renforcement complet',
    focus: "La séance force.",
    duration: 600,
    exercises: [
      E.warmTwist,
      E.neckStretch,
      E.lionFace,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.deadBug,
      E.sidePlank,
      E.hollowHold,
      E.birdDog,
      E.lunge,
      E.gluteBridge,
      E.pushups,
      E.coolStretch,
    ],
    quote: "La force n'arrive pas de ce que tu peux faire, mais de surmonter ce que tu ne pensais pas pouvoir.",
  },
  {
    day: 28,
    phase: 'Maîtrise',
    title: 'Avant-dernier round',
    subtitle: 'HIIT + force',
    focus: "Combo explosif.",
    duration: 600,
    exercises: [
      E.warmBreath,
      E.chinLift,
      E.tonguePress,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.shoulderTaps,
      E.plankUp,
      E.plank,
      E.bicycleCrunch,
      E.wallSit,
      E.tricepDips,
      E.calfRaises,
      E.coolBreath,
    ],
    quote: 'Plus que deux jours. Ta transformation est presque complète.',
  },
  {
    day: 29,
    phase: 'Maîtrise',
    title: 'La grande épreuve',
    subtitle: 'Tout en intensité',
    focus: "Donne tout ce qu'il te reste.",
    duration: 600,
    exercises: [
      E.warmMarch,
      E.fishFace,
      E.cheekLift,
      E.jumpingJacks,
      E.highKnees,
      E.mountainClimbers,
      E.russianTwist,
      E.legRaises,
      E.flutterKicks,
      E.deadBug,
      E.superman,
      E.reverseLunge,
      E.sumoSquat,
      E.coolStretch,
    ],
    quote: "Aujourd'hui, tu découvres de quoi tu es vraiment capable.",
  },
  {
    day: 30,
    phase: 'Maîtrise',
    title: 'Jour 30 — Ta victoire',
    subtitle: 'Célébration finale',
    focus: "Le flow final.",
    duration: 600,
    exercises: [
      E.warmTwist,
      E.jawRelease,
      E.neckStretch,
      E.squatJumps,
      E.burpees,
      E.skaters,
      E.sidePlank,
      E.hollowHold,
      E.birdDog,
      E.shoulderTaps,
      E.gluteKickback,
      E.squat,
      E.lunge,
      E.coolBreath,
    ],
    quote: "30 jours. Tu l'as fait. Ce n'est pas une fin, c'est un début.",
  },
];


/* ------------------------------------------------------------------ */
/*  HELPERS                                                            */
/* ------------------------------------------------------------------ */

export const PHASES: Record<ProgramPhase, {
  label: string;
  description: string;
  color: string;
  gradient: string;
  days: string;
}> = {
  Fondation: {
    label: 'Fondation',
    description: "Apprentissage des mouvements en douceur",
    color: 'emerald',
    gradient: 'from-emerald-500 to-teal-500',
    days: 'Jours 1-7',
  },
  Progression: {
    label: 'Progression',
    description: "Intensité modérée et nouveaux exercices",
    color: 'amber',
    gradient: 'from-amber-500 to-orange-500',
    days: 'Jours 8-14',
  },
  Intensification: {
    label: 'Intensification',
    description: "HIIT, explosivité et amplitude",
    color: 'orange',
    gradient: 'from-orange-500 to-rose-500',
    days: 'Jours 15-21',
  },
  Maîtrise: {
    label: 'Maîtrise',
    description: "Intensité maximale et performance",
    color: 'rose',
    gradient: 'from-rose-500 to-pink-600',
    days: 'Jours 22-30',
  },
};

export const TOTAL_DAYS = program.length;
export const TOTAL_DURATION = program.reduce((s, d) => s + d.duration, 0);
export const TOTAL_EXERCISES = program.reduce(
  (s, d) => s + d.exercises.length,
  0,
);

export function getDay(day: number): DayProgram | undefined {
  return program.find((d) => d.day === day);
}

export function getNextDay(completedDays: number[]): number | null {
  for (let i = 1; i <= TOTAL_DAYS; i++) {
    if (!completedDays.includes(i)) return i;
  }
  return null;
}
